## local
#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/datajpa
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        #show_sql:true
#        format_sql: true
#
#logging.level:
#  org.hibernate.SQL: debug

# aws server
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/university?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #show_sql:true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug